### ISSUE TITLE
Huma calculation fails

### ISSUE THREAD

**Issue by maths22** [kevmo314/canigraduate.uchicago.edu-old#12]
HUMA 19100 (the no-credit writing seminar) is counted as a hum course, meaning it says I am done with hum after only 1 quarter.

**Comment by kevmo314** [comment]
Are you importing your data or entering it manually? If you're entering it manually, this is the desired behavior because you're telling canigraduate to treat it as a credited class. Uncredited classes do not appear on import.

**Comment by maths22** [comment]
I'm importing it.

**Comment by kevmo314** [comment]
Okay should be fixed in the latest commit, thanks.
