### ISSUE TITLE
Cross listed classes have separate distros for grades

### ISSUE THREAD

**Issue by loosecannon93** [kevmo314/canigraduate.uchicago.edu-old#15]
eg. CMSC/MATH-277 has different grade lists depending on which dept you look it up under. 

Seems like this would be better to combine them.

**Comment by kevmo314** [comment]
This ends up resulting in a disparity between the EGPA displayed on the transcript page and the mean GPA on the class listing, as EGPA is the best estimate of students just like you, so crosslistings should not be included, but I think it's okay.
